/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    TButton: typeof import('tdesign-vue-next')['Button']
    TCollapse: typeof import('tdesign-vue-next')['Collapse']
    TCollapsePanel: typeof import('tdesign-vue-next')['CollapsePanel']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TNotification: typeof import('tdesign-vue-next')['Notification']
    TSpace: typeof import('tdesign-vue-next')['Space']
  }
}
