name: Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up pnpm
        uses: pnpm/setup@v1
        with:
          version: 11
          runtime: node@24
          cache: true

      - name: Install dependencies
        run: pnpm bootstrap

      - name: Run tests
        run: pnpm test

      - name: Update index definitions
        run: pnpm update:index-definitions

      - name: Build
        run: pnpm build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist
          if-no-files-found: error
          compression-level: 9

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
